export type KeyStats = {
    marketCap: number | null,
    peRatio: number | null,
    week52High: number | null,
    week52Low: number | null,
    avgTotalVolume: number | null,
    previousClose: number | null,
    low: number | null,
    high: number | null,
    volume: number | null,
    open: number | null,
    dividendYield: number | null,
    actualEPS: number | null,
    primaryExchange: string | null,
    latestTime: string | null,
    isUSMarketOpen: boolean,
    isFetchingQuote: boolean,
}
