export const UPDATE_TICKER = 'UPDATE_TICKER';
export const UPDATE_KEY_STATS = 'UPDATE_KEY_STATS';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const UPDATE_PEERS = 'UPDATE_PEERS';
export const UPDATE_CHART_RANGE = 'UPDATE_CHART_RANGE';
export const UPDATE_CHART_DATA = 'UPDATE_CHART_DATA';